before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

language: ruby
rvm:
  - 1.9.3
  - "2.1.2"
  - rbx
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec